import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import '@/styles/globals.css';
import { RecoilRootWrapper } from '@/state';
import { Container, Navbar } from '@/components';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.className} bg-white text-black dark:bg-black dark:text-white main-transition`}
      >
        <RecoilRootWrapper>
          <Container>
            <Navbar />
            {children}
          </Container>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
